name: release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: windows-latest
    permissions: 
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Install python and dependencies
      run: uv sync

    - name: Build binary
      uses: .\build_win.bat

    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ./dist/midihum_gui/*
