name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Install python packages
      run: uv sync

    - name: Build binary
      run: .\build_win.bat

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ./dist/midihum_gui/*
